{% set version = "2.28" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mcmcglmm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MCMCglmm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MCMCglmm/MCMCglmm_{{ version }}.tar.gz
  sha256: 7d92e6d35638e5e060a590b92c3b1bfc02a11386276a8ab99bceec5d797bfc2a

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-ape
    - r-coda
    - r-corpcor
    - r-cubature
    - r-tensora
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-ape
    - r-coda
    - r-corpcor
    - r-cubature
    - r-tensora

test:
  commands:
    - $R -e "library('MCMCglmm')"           # [not win]
    - "\"%R%\" -e \"library('MCMCglmm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MCMCglmm
  license: GPL (>= 2)
  summary: 'MCMC Generalised Linear Mixed Models.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
