travis:
  secure:
    BINSTAR_TOKEN: A2auI9q7BkcNbNab94VWUKtu3gf9DDbdbL6xVegI+vcoaFITlURDumpywPg6pcpBl2fU2jQH7whZJrDMdv+QbBw4tUWhm9hDqe/l5ClNQVJpq8mmQbI605F9MceTLDWaHlt6q0fXt/5QUK0cfWTDx05DwEk+p8A74F6wfHbqdevYwgyElWBbJ45DhYc47kPh8jMDvpD6SWgn+XNE28d842F7bsTiPvtOzUuX4TT4dXpLB2Y7PjUTx64wP45lSMoSIAT91SI2pEDuMv8+BYJjoekM3qy6flPhowYys1JFz5IEyo0RRhCtAjUScy9J+bw4pGBWT9XKB6RiDqIqFuOcqqWWij3bmBU1/71HDdz42AmddjoTVV8985E5X8agtD5LXpaWQshuI+lriuQ1MelcQqZtl+hRpEOXmoq8bkyDh0GU5+QHGVTln/iByRUBsuOSBRgmY4jdArzzAgbuqg8BQcyZEzAbKv0eRWYy+KAn1Ho3w0aQRrokO8D/sdIgc1jJw0pWGpvQUiJhcr9zsqoxMarp4yElAxCutE/dr4M2++fwH5VM8VSThoJHc9SHPQ4scR9Ak1LU/KCy9EalsKx6W9+7JBbQ+ffOj04DQQi+8X5o2TITzENSEmx9gDy7vMAZeIxKIzykq9dN23IfDmLic3iRm/cOQ2aG+qDEMBi1zo4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
