appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: WV9ExA2XxV72x39lWNNXWia+ZhZtY2HidoUH4Duk/mKzlrWnwAtqTMelmYqUTtuBYrHu2AHrezn8cAU0J84qVUssd5Q7lYRL0LNnD7Jt4oFtg8QdA92sBHQ5XsBjLZMLDxtUvVzWywdCneC6lefXnIUionrrrpPXo/jdnszNHKAxbIkN5M5gEKuOkTL1I3QBuBGUQ2fL4Y/qJMnggaX/bOo//Sor8z99UDJ35j/AEylkSN6NmcEyBJ0qIRP9fTBhm7rf3ejKvRf9jpV1linoHAAJgfC5PGdFHBLuL/3XxlfHrR90FovZP+363w+ZlW5xSYKR7rNrBxqWugLoJsUdacH120r4xAcFhS4k7EdtASKkb4XaN6zOV40JW31JLjryMVnlvAOrBMGGhHjBfs+5hS/JR/h7A1JJCsi74k74wFu+4VyGt0/5YKWOYwu3+g7tKSC1711P9xe0ptckVCxajC+JTZk9UOlc6ZTVeM1p/HNAz2i4+mxynsk4J7694ZIOoeHisqUgdE8UoFgTUD/gUVhaGLtqstonfLsIleUVMp/a2hKLEOpfQ2JIy7w6nVqwoyMR2fzEbvcwKwsV5XqPhUCkWujV9BtenJv2kOxrU92CLld8HsnCSqmIx3pr7hCWDtPwM79GSZ6Y936ARStq2icndf5f4uNwvxt8yrDrl4o=
